version: '3.7'
services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: datpv
            POSTGRES_PASSWORD: lifecafe
            POSTGRES_DB: life-cafe
        container_name: datpv-postgres

    adminer:
        image: adminer
        ports:
            - 8080:8080
        container_name: datpv-adminer

    db-test:
        image: postgres
        environment:
          POSTGRES_PASSWORD: lifecafetest
          POSTGRES_DB: life-cafe-test
        ports:
          - 5439:5432

    #     pgAdmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 8080:80
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: phungvandat97@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: phungvandatpv
    #     container_name: datpv-pgAdmin
