version: '3.7'
services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: datpv
            POSTGRES_PASSWORD: lifecafe
            POSTGRES_DB: life-cafe
        container_name: datpv-postgres
    
    adminer:
        image: adminer
        ports:
            - 8080:8080
        container_name: datpv-adminer